# Generated by Django 4.1 on 2022-10-30 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=120, verbose_name='Vehicle Type')),
                ('vehicle_no', models.CharField(max_length=120, verbose_name='Vehicle No')),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('driver_id', models.IntegerField(max_length=5, primary_key=True, serialize=False, verbose_name='Driver Id')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('license_no', models.IntegerField(max_length=11, verbose_name='Licence')),
                ('contact_no', models.IntegerField(max_length=12, verbose_name='Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('attendees', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cab.vehicle')),
            ],
        ),
    ]
