# Generated by Django 4.1 on 2022-10-31 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact', models.IntegerField(max_length=12, verbose_name='Number')),
                ('aadhar_no', models.IntegerField(primary_key=True, serialize=False)),
                ('boarding_point', models.CharField(max_length=120, verbose_name='from')),
                ('destination', models.CharField(max_length=120, verbose_name='to')),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.TimeField(verbose_name='time')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cab.vehicle')),
            ],
        ),
    ]
