# Generated by Django 4.1 on 2022-10-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0004_alter_drivers_license_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='contact',
            field=models.IntegerField(verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='contact_no',
            field=models.IntegerField(verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='license_no',
            field=models.IntegerField(verbose_name='Licence'),
        ),
    ]
