# Generated by Django 4.1 on 2022-10-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0005_alter_destination_contact_alter_drivers_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='driver_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Driver Id'),
        ),
    ]
