# Generated by Django 4.1 on 2022-10-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0006_alter_drivers_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='contact',
            field=models.IntegerField(max_length=12, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='contact_no',
            field=models.IntegerField(max_length=12, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='driver_id',
            field=models.IntegerField(max_length=5, primary_key=True, serialize=False, verbose_name='Driver Id'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='license_no',
            field=models.IntegerField(max_length=11, verbose_name='Licence'),
        ),
    ]
