# Generated by Django 4.1 on 2022-10-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0007_alter_destination_contact_alter_drivers_contact_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('password1', models.CharField(max_length=120, verbose_name='password1')),
                ('password2', models.CharField(max_length=120, verbose_name='Password2')),
            ],
        ),
        migrations.AlterField(
            model_name='drivers',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='cab.cabuser'),
        ),
    ]
