# Generated by Django 4.1 on 2022-11-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0010_destination_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivers',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Drivers',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
