# Generated by Django 4.1 on 2022-11-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0012_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vname', models.CharField(max_length=120)),
                ('Vno', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='travelinfo',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
