# Generated by Django 4.1 on 2022-11-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0015_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
