# Generated by Django 4.1 on 2022-11-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0016_veh_delete_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=120)),
                ('cardName', models.CharField(max_length=120)),
                ('cardNumber', models.IntegerField()),
                ('ExpDate', models.DateField()),
                ('cvv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Veh',
        ),
    ]
