# Generated by Django 4.1 on 2022-11-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0017_payment_vehicle_delete_veh'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrviersDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('licence', models.IntegerField()),
                ('aadhar', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='travelinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='travelinfo',
            name='name',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
